# short cuts
alias rc='rsync'
alias ..='cd ..'
alias c='clear'
alias vi='vim'

# New commands
alias pb='curl -F c=@- https://ptpb.pw < ' # pb a file and print url
alias pbv='vim tmp.txt && curl -F c=@- https://ptpb.pw < tmp.txt && rm tmp.txt' # open a tmp file in vim, upload to pb + print url, remove file
alias path='echo -e ${PATH//:/\\n}' # print path variable
alias si='du -sm * | sort -nr' # print directories by file size
alias sir='du -sm .[!.]* * | sort -nr' # same but with hidden stuff too
alias hlocate='find . -name ' # search for stuff
alias free='df -h' # free hard drive space
alias myip='curl http://ipecho.net/plain; echo' # print ip address
alias weather='curl -s wttr.in/Jonestown | head -7' # print weather
alias weather2='curl -s wttr.in/Jonestown | head -17 | tail -10' # print weather differently
